### PR TITLE
'Doc' and 'Tutorials' menu items should have orange bullet for active state

### PR DESCRIPTION
**Pull request by Bgreen23**
This PR adds bullet to Docs and Tutorials nav active state

Docs Preview: https://605a5ebeb0ce0500aa3157f0--shiftlab-pytorch-docs.netlify.app/

**Updated Preview:** https://605e0942b7a3ad00a3f4489f--shiftlab-pytorch-docs.netlify.app/

### CODE REVIEW

**Review by patmellon — CHANGES_REQUESTED** [review]
Can you center the bullet underneath the Docs/Tutorials text? Right now it looks like the centering is taking the arrow into account, but it looks off. There's a bullet that appears under the Resources link, and that looks like it's centered under the text only: https://pytorch.org/features/ 

Maybe you can take the same approach as this PR: https://github.com/pytorch/pytorch.github.io/pull/623/files

**Comment by jmjackson6880** [comment]
@Bgreen23 Here are some "designs" that will help you dial this in further. Per @patmellon feedback, please use the PR linked (and was also referenced in the story) for the CSS.


docs-feedback

tutorials-feedback

**Comment by Bgreen23** [comment]
Updated Docs preview: https://605c91a4392c5617be5403f1--shiftlab-pytorch-docs.netlify.app/
I can't generate a preview for tutorials due to an issue with my tutorials set up

**Comment by jmjackson6880** [comment]
Docs nav looks good. Can you provide at least a screenshot for the Tutorials nav?

**Comment by patmellon** [comment]
Looks good. The Resources dropdown isn't working, though. Is that just an issue with your preview?

**Comment by Bgreen23** [comment]
Screenshot of tutorials with the `display:none` removed from the active state 
Screen Shot 2021-03-26 at 12 37 44 PM

**Comment by patmellon** [comment]
@Bgreen23 Can you look into what's going on in the Tutorials screenshot? The Docs dropdown arrow is orange instead of black.

**Comment by Bgreen23** [comment]
> @Bgreen23 Can you look into what's going on in the Tutorials screenshot? The Docs dropdown arrow is orange instead of black.

This is a bug that we have slotted in https://shiftlabny.atlassian.net/secure/RapidBoard.jspa?rapidView=43&projectKey=PYT&modal=detail&selectedIssue=PYT-564. I plan on opening a separate PR at some point to address this

**Comment by jmjackson6880** [comment]
> @Bgreen23 Can you look into what's going on in the Tutorials screenshot? The Docs dropdown arrow is orange instead of black.

Good catch, but @Bgreen23 please deliver that as a separate story. This problem exists now:
https://pytorch.org/tutorials/

Let's please get the bullets PR filed ASAP.

**Review by patmellon — APPROVED** [review]

**Pull request merged**
